services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $someParameter: 'default value'

    App\:
        resource: '../src/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Déclaration correcte du service HuggingFace
    App\Service\OpenRouterService:
        arguments:
            $openRouterApiKey: '%env(OPENROUTER_API_KEY)%'