# config/services.yaml

parameters:
    apivideo.api_key: '%env(APIVIDEO_API_KEY)%'
    ably.api_key: '%env(ABLY_API_KEY)%'
    ai.api_key: '%env(AI_API_KEY)%'
    ai.api_url: '%env(AI_API_URL)%'
    profiles_directory: '%kernel.project_dir%/public/uploads/profiles'
    videos_directory: '%kernel.project_dir%/public/uploads/videos'
    playlist_images_directory: '%kernel.project_dir%/public/uploads/playlists'
    groq_api_key: '%env(GROQ_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\OpenRouterService:
        arguments:
            $openRouterApiKey: '%env(OPENROUTER_API_KEY)%'

    App\Controller\SubtitleController:
        arguments:
            $groqApiKey: '%groq_api_key%'