# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    # tes paramètres ici si besoin
    profiles_directory: '%kernel.project_dir%/public/uploads/profile_images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $someParameter: 'default value'

    App\:
        resource: '../src/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
